### ISSUE TITLE
Snapchat crashes while trying to launch

### ISSUE THREAD

**Issue by forumber** [marzika/Snapprefs#150]
Using latest Snapprefs build from build server;

```
-----------------
15 Ağu 2016 17:19:59 UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'JZO54K.I8160XXMH1' with fingerprint 'samsung/GT-I8160/GT-I8160:4.1.2/JZO54K/I8160XXMH1:user/release-keys'
Loading modules from /data/app/com.marz.snapprefs-1.apk
  Loading class com.marz.snapprefs.HookMethods
----------------- SNAPPREFS HOOKED -----------------
SnapChat Version: 9.31.1.0 (847)
SnapPrefs Version: 1.6.5 (24)

-------------- SNAPPREFS SETTINGS
FullCaption: false
SelectAll: false
SelectStory: false
SelectVenue: false
HideBF: false
HideRecent: false
ShouldAddGhost: false
TxtColours: false
BgColours: false
Size: false
Transparency: false
Rainbow: false
Background Transparency: false
TextStyle: false
TextGravity: false
mTimerCounter: true
mChatAutoSave: true
mChatImageSave: true
mIntegration: true
mPaintTools: false
CustomFilters: false
MultiFilters: false
CustomFiltersLocation: /storage/sdcard0/Snapprefs/Filters
CustomFilterType: 0
mSpeed: false
mWeather: false
mLocation: false
mStoryPreload: false
mDiscoverSnap: false
mDiscoverUI: false
mCustomSticker: false
mHideLive: false
mHidePeople: false
mReplay: false
mStealth: false
mTyping: false
mUnlimGroups: false
mForceNavbar: 0
mColours: false
*****Debugging: true *****
mLicense: 0

----------------------- SAVING SETTINGS -----------------------
Preferences have changed:
~ mModeSnapImage: SAVE_AUTO
~ mModeSnapVideo: SAVE_AUTO
~ mModeStoryImage: SAVE_AUTO
~ mModeStoryVideo: SAVE_AUTO
~ mOverlays: false
~ mTimerMinimum: 10
~ mToastEnabled: false
~ mVibrationEnabled: false
~ mToastLength: 0
~ mSavePath: /mnt/sdcard/keepchat
~ mSaveSentSnaps: true
~ mSortByCategory: true
~ mSortByUsername: true
~ mTimerUnlimited: false
~ mHideTimerStory: false
~ mLoopingVids: false
~ mHideTimer: false
SnapPrefs: ROOTCHECK: b
SnapPrefs: ROOTCHECK: c
SnapPrefs: ROOTCHECK: d
SnapPrefs: ROOTCHECK: e
SnapPrefs: SECOND_MAX_VIDEO_DURATION set over 10
java.lang.ExceptionInInitializerError
    at java.lang.reflect.Field.setIField(Native Method)
    at java.lang.reflect.Field.setInt(Field.java:781)
    at de.robv.android.xposed.XposedHelpers.setStaticIntField(XposedHelpers.java:797)
    at com.marz.snapprefs.HookMethods$1.afterHookedMethod(HookMethods.java:563)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
    at android.app.Application.attach(Native Method)
    at android.app.Instrumentation.newApplication(Instrumentation.java:998)
    at android.app.Instrumentation.newApplication(Instrumentation.java:982)
    at android.app.LoadedApk.makeApplication(LoadedApk.java:496)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4170)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
    at android.app.ActivityThread.handleBindApplication(Native Method)
    at android.app.ActivityThread.access$1400(ActivityThread.java:134)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4867)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
    at QR.<init>(SourceFile:84)
    at QR.<init>(SourceFile:74)
    at com.snapchat.android.camera.transcoding.TranscodingPreferencesWrapper.a(SourceFile:224)
    at com.snapchat.android.camera.transcoding.TranscodingPreferencesWrapper.<init>(SourceFile:40)
    at com.snapchat.android.camera.transcoding.TranscodingPreferencesWrapper.<init>(SourceFile:33)
    at com.snapchat.android.camera.transcoding.TranscodingPreferencesWrapper.a(SourceFile:52)
    at com.snapchat.android.util.SnapMediaUtils.<clinit>(SourceFile:57)
    ... 24 more
SnapPrefs: SNAPCONTEXT, NULL? - false
SnapPrefs: SNAPCONTEXT, NULL? - false

```

**Comment by Markersx** [comment]
@forumber Your snapchat version is 9.31.1.0 it needs to be 9.2.1.0 or lower.

**Comment by forumber** [comment]
@Markersx Latest Snapprefs build is compatible with 9.31.1.0 ;

https://github.com/marzika/Snapprefs/blob/stable/app/src/main/java/com/marz/snapprefs/Obfuscator.java#L23

**Comment by Markersx** [comment]
Have you tried using a lover version?

**Comment by marzika** [comment]
Mark, please, don't even say anything. I will look into the issue tomorrow.

**Comment by avi312singh** [comment]
@Markersx If you looked at the Obfuscator class the supported version is 9.31.1.0 or higher... The first method checks for this...

**Comment by AmineI** [comment]
Same here ! I can provide more logs if you need it.

**Comment by marzika** [comment]
Could you please clear your Snapchat data completly and relog into it (DON'T restore your previously backuped login)? Seems like your Transcoding preferences are wrong therefore a class' static variable isn't getting created.

**Comment by forumber** [comment]
@marzika I uninstalled Xposed --> rebooted the device --> cleared all Snapchat data --> relogged in --> re-installed Xposed & activated Snapprefs --> rebooted the device --> try to launch it

Exact same issue. Here's the full logcat;

[logcat.txt](https://github.com/marzika/Snapprefs/files/420440/logcat.txt)

**Comment by marzika** [comment]
This should suppress the error, however I recommend you to upgrade your device to a newer android version. https://github.com/marzika/Snapprefs/commit/cb19db45caec03dc818d8b22f5ec7a45e8704c3b

**Comment by forumber** [comment]
@marzika Thanks for quick update. But, there's another problem now;

```
I/dalvikvm( 4316): Rejecting re-init on previously-failed class Lcom/snapchat/android/util/SnapMediaUtils; v=0x0
D/AndroidRuntime( 4316): Shutting down VM
W/dalvikvm( 4316): threadid=1: thread exiting with uncaught exception (group=0x40f512a0)
E/AndroidRuntime( 4316): FATAL EXCEPTION: main
E/AndroidRuntime( 4316): java.lang.NoClassDefFoundError: com/snapchat/android/util/SnapMediaUtils
E/AndroidRuntime( 4316):    at com.snapchat.android.ui.camera.TakeSnapButton.onSizeChanged(SourceFile:80)
E/AndroidRuntime( 4316):    at android.view.View.setFrame(View.java:13948)
E/AndroidRuntime( 4316):    at android.view.View.layout(View.java:13860)
E/AndroidRuntime( 4316):    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
E/AndroidRuntime( 4316):    at android.view.View.layout(View.java:13862)
E/AndroidRuntime( 4316):    at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime( 4316):    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
E/AndroidRuntime( 4316):    at android.view.View.layout(View.java:13862)
E/AndroidRuntime( 4316):    at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime( 4316):    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AndroidRuntime( 4316):    at android.view.View.layout(View.java:13862)
E/AndroidRuntime( 4316):    at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime( 4316):    at com.snapchat.android.ui.VerticalSwipeLayout.onLayout(SourceFile:238)
E/AndroidRuntime( 4316):    at android.view.View.layout(View.java:13862)
E/AndroidRuntime( 4316):    at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime( 4316):    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AndroidRuntime( 4316):    at android.view.View.layout(View.java:13862)
E/AndroidRuntime( 4316):    at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime( 4316):    at android.support.v4.view.ViewPager.onLayout(SourceFile:1695)
E/AndroidRuntime( 4316):    at android.view.View.layout(View.java:13862)
E/AndroidRuntime( 4316):    at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime( 4316):    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AndroidRuntime( 4316):    at android.view.View.layout(View.java:13862)
E/AndroidRuntime( 4316):    at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime( 4316):    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AndroidRuntime( 4316):    at android.view.View.layout(View.java:13862)
E/AndroidRuntime( 4316):    at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime( 4316):    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AndroidRuntime( 4316):    at android.view.View.layout(View.java:13862)
E/AndroidRuntime( 4316):    at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime( 4316):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
E/AndroidRuntime( 4316):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
E/AndroidRuntime( 4316):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
E/AndroidRuntime( 4316):    at android.view.View.layout(View.java:13862)
E/AndroidRuntime( 4316):    at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime( 4316):    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AndroidRuntime( 4316):    at android.view.View.layout(View.java:13862)
E/AndroidRuntime( 4316):    at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime( 4316):    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1992)
E/AndroidRuntime( 4316):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1813)
E/AndroidRuntime( 4316):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1113)
E/AndroidRuntime( 4316):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4481)
E/AndroidRuntime( 4316):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
E/AndroidRuntime( 4316):    at android.view.Choreographer.doCallbacks(Choreographer.java:555)
E/AndroidRuntime( 4316):    at android.view.Choreographer.doFrame(Choreographer.java:525)
E/AndroidRuntime( 4316):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
E/AndroidRuntime( 4316):    at android.os.Handler.handleCallback(Handler.java:615)
E/AndroidRuntime( 4316):    at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 4316):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 4316):    at android.app.ActivityThread.main(ActivityThread.java:4867)
E/AndroidRuntime( 4316):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4316):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 4316):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
E/AndroidRuntime( 4316):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
E/AndroidRuntime( 4316):    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
E/AndroidRuntime( 4316):    at dalvik.system.NativeStart.main(Native Method)
```

There's no problem with only Xposed (without Snapprefs) btw.

Here's full dumpstate log if you want to look at it.
[dumpstate_app_error.txt.gz](https://github.com/marzika/Snapprefs/files/420789/dumpstate_app_error.txt.gz)

**Comment by AmineI** [comment]
I have the same issue after updating

**Comment by marzika** [comment]
The issue is related to lower android version, which I cannot test and are obsolate. I will not rewrite the module to work on a version that is being used by less than 1%.

**Comment by AmineI** [comment]
(Actually, Jelly Bean is around 16% market share, from Google's August datas https://developer.android.com/about/dashboards/index.html#Platform . )

OK ! Thank you anyway for supporting older versions for so long :)
