### ISSUE TITLE
Snapchat obfuscation breaking method searching

### ISSUE THREAD

**Issue by Fuzion24** [marzika/Snapprefs#22]
Hello,
It looks like snapchat has been updated and thus the proguard obfuscated classes have changed. May I suggested adding some functionality to heuristically look for the classes and methods you need.  For example for : 

```
//ScreenshotDetector class
        public static final String SCREENSHOTDETECTOR_CLASS = "ara";
```

You could look through all the classes and search for certain strings or function signatures.  Like return me the class which has the string "blah" as a field initializer with a function of return value boolean that takes two parameters int and string.

```
I/Xposed  (14564): ----------------- SNAPPREFS HOOKED -----------------
I/Xposed  (14564): SnapChat Version: 9.15.1.0 (720)
I/Xposed  (14564): SnapPrefs Version: 1.4.7 (15)
E/Xposed  (14564): java.lang.NoSuchMethodError: ara#a(java.util.List)#exact
E/Xposed  (14564):  at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:181)
E/Xposed  (14564):  at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:131)
E/Xposed  (14564):  at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:138)
E/Xposed  (14564):  at com.marz.snapprefs.HookMethods.handleLoadPackage(HookMethods.java:244)
E/Xposed  (14564):  at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
E/Xposed  (14564):  at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
E/Xposed  (14564):  at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
E/Xposed  (14564):  at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:174)
E/Xposed  (14564):  at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:648)
E/Xposed  (14564):  at android.app.ActivityThread.handleBindApplication(<Xposed>)
E/Xposed  (14564):  at android.app.ActivityThread.access$1500(ActivityThread.java:151)
E/Xposed  (14564):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
E/Xposed  (14564):  at android.os.Handler.dispatchMessage(Handler.java:102)
E/Xposed  (14564):  at android.os.Looper.loop(Looper.java:135)
E/Xposed  (14564):  at android.app.ActivityThread.main(ActivityThread.java:5254)
E/Xposed  (14564):  at java.lang.reflect.Method.invoke(Native Method)
E/Xposed  (14564):  at java.lang.reflect.Method.invoke(Method.java:372)
E/Xposed  (14564):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/Xposed  (14564):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/Xposed  (14564):  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
```

**Comment by marzika** [comment]
Heuristic checks are not possibel, since there are thousands of methods which accept the same argyments. Also, the arguments' class name is changing too.

The classes have already been updated: https://github.com/marzika/Snapprefs/commit/fd96eeef517bc505860a3e3c034606560c3ae463
