### ISSUE TITLE
Snapchat crashes sometimes without reason, LOG ATTACHED

### ISSUE THREAD

**Issue by MrMikeTyson** [marzika/Snapprefs#349]
Snapchat crashes sometimes without reason.
[Log_2016-12-01_17-07-37.0.txt](https://github.com/marzika/Snapprefs/files/625446/Log_2016-12-01_17-07-37.0.txt)

**Comment by marzika** [comment]
Post a properly filtered logcat, not one that has 1/10th of the stacktrace.

**Comment by MrMikeTyson** [comment]
[Log_2016-12-02_06-26-37.txt](https://github.com/marzika/Snapprefs/files/626430/Log_2016-12-02_06-26-37.txt)

**Comment by M1kep** [comment]
How are you going about getting your log files?

**Comment by MrMikeTyson** [comment]
with Logcat Extreme

**Comment by marzika** [comment]
The crash seems to be caused by your SystemUI.

**Comment by marzika** [comment]
Also, your first log shows different errors... Please use logcat properly from commandline not applications that are halfassly developed.

**Comment by MrMikeTyson** [comment]
I made this logcat with LogcatExtreme, and I guess that LogcatExtreme is not a halfassly developed application, to filter I typed the word "snap" and I saved the logcat. Snapchat works normally without snapprefs, when I install SnapPrefs and activate it in xposed, Snapchat makes errors of the sort to crash without reason, i have Android Marshmallow 6.0 and LG G3 D855

**Comment by marzika** [comment]
Just as an example, take a look at this log:
Original:
<code>
6333/DCIM/SentSnaps/2016-09-17_01-03-08.jpg: open failed: EACCES (Permission denied)
09-17 01:03:08.106 E/Xposed  (29174): 	at libcore.io.IoBridge.open(IoBridge.java:452)
09-17 01:03:08.106 E/Xposed  (29174): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
09-17 01:03:08.106 E/Xposed  (29174): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
09-17 01:03:08.106 E/Xposed  (29174): 	at com.marz.snapprefs.Saving$saveImageJPGTask.doInBackground(Saving.java:928)
09-17 01:03:08.106 E/Xposed  (29174): 	at com.marz.snapprefs.Saving$saveImageJPGTask.doInBackground(Saving.java:920)
09-17 01:03:08.106 E/Xposed  (29174): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
09-17 01:03:08.106 E/Xposed  (29174): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-17 01:03:08.106 E/Xposed  (29174): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
09-17 01:03:08.106 E/Xposed  (29174): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-17 01:03:08.106 E/Xposed  (29174): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-17 01:03:08.106 E/Xposed  (29174): 	at java.lang.Thread.run(Thread.java:818)
09-17 01:03:08.106 E/Xposed  (29174): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
09-17 01:03:08.106 E/Xposed  (29174): 	at libcore.io.Posix.open(Native Method)
09-17 01:03:08.106 E/Xposed  (29174): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
09-17 01:03:08.106 E/Xposed  (29174): 	at libcore.io.IoBridge.open(IoBridge.java:438)
</code>

If we filter for "snap" with Catlog, etc.(Haven't found a proper reader yet)

<code>
6333/DCIM/SentSnaps/2016-09-17_01-03-08.jpg: open failed: EACCES (Permission denied)
09-17 01:03:08.106 E/Xposed  (29174): 	at com.marz.snapprefs.Saving$saveImageJPGTask.doInBackground(Saving.java:928)
09-17 01:03:08.106 E/Xposed  (29174): 	at com.marz.snapprefs.Saving$saveImageJPGTask.doInBackground(Saving.java:920)
</code>

As you can see only the lines containing the string "snap" are shown, the error reason, where it happens, etc are stripped off. That's why we need a manually filtered one from adb (it's easier to trim it in notepad than in your phone's text editor)

I test the module on Marshmallow myself, but apart from issues that origin from my rom I haven't noticed crashing. To solve the issue, we need that logcat.

**Comment by MrMikeTyson** [comment]
Okay, I just figured out, as snapchat doesn't crash all the time but just sometimes, I'll do a logcat when it crash, i'll filter and then I'll post it. Thanks

**Comment by MrMikeTyson** [comment]
Snapchat crashed when i was sharing a video, Here is the new logcat :

12-10 01:10:20.175  7741  8665 I ActivityManager: START u0 {act=android.intent.action.SEND typ=video/* flg=0xb080001 cmp=com.marz.snapprefs/.ReceiveMediaActivity clip={video/* U:content://media/external/video/media/3330} (has extras)} from uid 10032 on display 0

12-10 01:10:20.244  7741  8687 I ActivityManager: Start proc 1925:com.marz.snapprefs/u0a116 for activity com.marz.snapprefs/.ReceiveMediaActivity

12-10 01:10:20.575  1925  1925 I Timeline: Timeline: Activity_launch_request id:com.snapchat.android time:8492999

12-10 01:10:20.576  7741  8652 I ActivityManager: START u0 {act=android.intent.action.SEND typ=video/* flg=0x10008000 cmp=com.snapchat.android/.LandingPageActivity clip={video/* U:content://media/external/video/media/3330} (has extras)} from uid 10116 on display 0

12-10 01:10:59.751  7741  8621 I WindowState: WIN DEATH: Window{28f8cf9 u0 com.snapchat.android/com.snapchat.android.LandingPageActivity}

12-10 01:10:59.835  7741  7752 I ActivityManager: Process com.snapchat.android (pid 30429) has died

12-10 01:10:59.860  7741  7752 W ActivityManager: Scheduling restart of crashed service com.snapchat.android/.service.ScStickyService in 1000ms

12-10 01:10:59.860  7741  7752 W ActivityManager: Scheduling restart of crashed service com.snapchat.android/.util.chat.SecureChatService in 10999ms

12-10 01:11:00.890  7741  7754 I ActivityManager: Start proc 2573:com.snapchat.android/u0a88 for service com.snapchat.android/.service.ScStickyService
