### ISSUE TITLE
SP not hooking properly. 

### ISSUE THREAD

**Issue by RyanBrogan** [marzika/Snapprefs#392]
So I just typed down a paragraph describing my problem twice and ended up refreshing this page trying to scroll up both times so I'll make it short. 

My SP doesn't seem to hook properly, my log does throw some errors regarding the hook but I really don't know of what I'm doing... 
It's been 2 months of me playing with it and trying to figure out what's borked (full wipes some reinstalls didn't help). 
So here's my log, thank you guys in advance. 

04-02 10:07:43.662 I/Xposed  ( 1188): -----------------
04-02 10:07:43.662 I/Xposed  ( 1188): Starting Xposed version 87, compiled for SDK 23
04-02 10:07:43.662 I/Xposed  ( 1188): Device: HTC One M9 (HTC), Android version 6.0.1 (SDK 23)
04-02 10:07:43.662 I/Xposed  ( 1188): ROM: MMB29M release-keys
04-02 10:07:43.662 I/Xposed  ( 1188): Build fingerprint: htc/pmeuhl_00401/htc_pmeuhl:6.0.1/MMB29M/797255.3:user/release-keys
04-02 10:07:43.662 I/Xposed  ( 1188): Platform: arm64-v8a, 64-bit binary, system server: yes
04-02 10:07:43.662 I/Xposed  ( 1188): SELinux enabled: yes, enforcing: no
04-02 10:07:46.041 I/Xposed  ( 1188): -----------------
04-02 10:07:46.041 I/Xposed  ( 1188): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
04-02 10:07:46.312 I/Xposed  ( 1188): Detected ART runtime
04-02 10:07:46.333 I/Xposed  ( 1188): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
04-02 10:07:46.935 I/Xposed  ( 1188): Loading modules from /data/app/com.marz.snapprefs-1/base.apk
04-02 10:07:46.965 I/Xposed  ( 1188):   Loading class com.marz.snapprefs.HookMethods
04-02 10:07:53.815 I/Xposed  ( 1189): -----------------
04-02 10:07:53.815 I/Xposed  ( 1189): Starting Xposed version 87, compiled for SDK 23
04-02 10:07:53.815 I/Xposed  ( 1189): Device: HTC One M9 (HTC), Android version 6.0.1 (SDK 23)
04-02 10:07:53.815 I/Xposed  ( 1189): ROM: MMB29M release-keys
04-02 10:07:53.815 I/Xposed  ( 1189): Build fingerprint: htc/pmeuhl_00401/htc_pmeuhl:6.0.1/MMB29M/797255.3:user/release-keys
04-02 10:07:53.815 I/Xposed  ( 1189): Platform: arm64-v8a, 32-bit binary, system server: no
04-02 10:07:53.815 I/Xposed  ( 1189): SELinux enabled: yes, enforcing: no
04-02 10:07:55.914 I/Xposed  ( 1189): -----------------
04-02 10:07:55.914 I/Xposed  ( 1189): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
04-02 10:07:56.023 I/Xposed  ( 1189): Detected ART runtime
04-02 10:07:56.027 I/Xposed  ( 1189): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
04-02 10:07:56.462 I/Xposed  ( 1189): Loading modules from /data/app/com.marz.snapprefs-1/base.apk
04-02 10:07:56.487 I/Xposed  ( 1189):   Loading class com.marz.snapprefs.HookMethods
04-02 10:07:43.662 I/Xposed  ( 1188): -----------------
04-02 10:07:43.662 I/Xposed  ( 1188): Starting Xposed version 87, compiled for SDK 23
04-02 10:07:43.662 I/Xposed  ( 1188): Device: HTC One M9 (HTC), Android version 6.0.1 (SDK 23)
04-02 10:07:43.662 I/Xposed  ( 1188): ROM: MMB29M release-keys
04-02 10:07:43.662 I/Xposed  ( 1188): Build fingerprint: htc/pmeuhl_00401/htc_pmeuhl:6.0.1/MMB29M/797255.3:user/release-keys
04-02 10:07:43.662 I/Xposed  ( 1188): Platform: arm64-v8a, 64-bit binary, system server: yes
04-02 10:07:43.662 I/Xposed  ( 1188): SELinux enabled: yes, enforcing: no
04-02 10:07:46.041 I/Xposed  ( 1188): -----------------
04-02 10:07:46.041 I/Xposed  ( 1188): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
04-02 10:07:46.312 I/Xposed  ( 1188): Detected ART runtime
04-02 10:07:46.333 I/Xposed  ( 1188): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
04-02 10:07:46.935 I/Xposed  ( 1188): Loading modules from /data/app/com.marz.snapprefs-1/base.apk
04-02 10:07:46.965 I/Xposed  ( 1188):   Loading class com.marz.snapprefs.HookMethods
04-02 10:07:53.815 I/Xposed  ( 1189): -----------------
04-02 10:07:53.815 I/Xposed  ( 1189): Starting Xposed version 87, compiled for SDK 23
04-02 10:07:53.815 I/Xposed  ( 1189): Device: HTC One M9 (HTC), Android version 6.0.1 (SDK 23)
04-02 10:07:53.815 I/Xposed  ( 1189): ROM: MMB29M release-keys
04-02 10:07:53.815 I/Xposed  ( 1189): Build fingerprint: htc/pmeuhl_00401/htc_pmeuhl:6.0.1/MMB29M/797255.3:user/release-keys
04-02 10:07:53.815 I/Xposed  ( 1189): Platform: arm64-v8a, 32-bit binary, system server: no
04-02 10:07:53.815 I/Xposed  ( 1189): SELinux enabled: yes, enforcing: no
04-02 10:07:55.914 I/Xposed  ( 1189): -----------------
04-02 10:07:55.914 I/Xposed  ( 1189): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
04-02 10:07:56.023 I/Xposed  ( 1189): Detected ART runtime
04-02 10:07:56.027 I/Xposed  ( 1189): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
04-02 10:07:56.462 I/Xposed  ( 1189): Loading modules from /data/app/com.marz.snapprefs-1/base.apk
04-02 10:07:56.487 I/Xposed  ( 1189):   Loading class com.marz.snapprefs.HookMethods
04-02 10:07:43.662 I/Xposed  ( 1188): -----------------
04-02 10:07:43.662 I/Xposed  ( 1188): Starting Xposed version 87, compiled for SDK 23
04-02 10:07:43.662 I/Xposed  ( 1188): Device: HTC One M9 (HTC), Android version 6.0.1 (SDK 23)
04-02 10:07:43.662 I/Xposed  ( 1188): ROM: MMB29M release-keys
04-02 10:07:43.662 I/Xposed  ( 1188): Build fingerprint: htc/pmeuhl_00401/htc_pmeuhl:6.0.1/MMB29M/797255.3:user/release-keys
04-02 10:07:43.662 I/Xposed  ( 1188): Platform: arm64-v8a, 64-bit binary, system server: yes
04-02 10:07:43.662 I/Xposed  ( 1188): SELinux enabled: yes, enforcing: no
04-02 10:07:46.041 I/Xposed  ( 1188): -----------------
04-02 10:07:46.041 I/Xposed  ( 1188): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
04-02 10:07:46.312 I/Xposed  ( 1188): Detected ART runtime
04-02 10:07:46.333 I/Xposed  ( 1188): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
04-02 10:07:46.935 I/Xposed  ( 1188): Loading modules from /data/app/com.marz.snapprefs-1/base.apk
04-02 10:07:46.965 I/Xposed  ( 1188):   Loading class com.marz.snapprefs.HookMethods
04-02 10:07:53.815 I/Xposed  ( 1189): -----------------
04-02 10:07:53.815 I/Xposed  ( 1189): Starting Xposed version 87, compiled for SDK 23
04-02 10:07:53.815 I/Xposed  ( 1189): Device: HTC One M9 (HTC), Android version 6.0.1 (SDK 23)
04-02 10:07:53.815 I/Xposed  ( 1189): ROM: MMB29M release-keys
04-02 10:07:53.815 I/Xposed  ( 1189): Build fingerprint: htc/pmeuhl_00401/htc_pmeuhl:6.0.1/MMB29M/797255.3:user/release-keys
04-02 10:07:53.815 I/Xposed  ( 1189): Platform: arm64-v8a, 32-bit binary, system server: no
04-02 10:07:53.815 I/Xposed  ( 1189): SELinux enabled: yes, enforcing: no
04-02 10:07:55.914 I/Xposed  ( 1189): -----------------
04-02 10:07:55.914 I/Xposed  ( 1189): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
04-02 10:07:56.023 I/Xposed  ( 1189): Detected ART runtime
04-02 10:07:56.027 I/Xposed  ( 1189): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
04-02 10:07:56.462 I/Xposed  ( 1189): Loading modules from /data/app/com.marz.snapprefs-1/base.apk
04-02 10:07:56.487 I/Xposed  ( 1189):   Loading class com.marz.snapprefs.HookMethods
04-02 10:07:43.662 I/Xposed  ( 1188): -----------------
04-02 10:07:43.662 I/Xposed  ( 1188): Starting Xposed version 87, compiled for SDK 23
04-02 10:07:43.662 I/Xposed  ( 1188): Device: HTC One M9 (HTC), Android version 6.0.1 (SDK 23)
04-02 10:07:43.662 I/Xposed  ( 1188): ROM: MMB29M release-keys
04-02 10:07:43.662 I/Xposed  ( 1188): Build fingerprint: htc/pmeuhl_00401/htc_pmeuhl:6.0.1/MMB29M/797255.3:user/release-keys
04-02 10:07:43.662 I/Xposed  ( 1188): Platform: arm64-v8a, 64-bit binary, system server: yes
04-02 10:07:43.662 I/Xposed  ( 1188): SELinux enabled: yes, enforcing: no
04-02 10:07:46.041 I/Xposed  ( 1188): -----------------
04-02 10:07:46.041 I/Xposed  ( 1188): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
04-02 10:07:46.312 I/Xposed  ( 1188): Detected ART runtime
04-02 10:07:46.333 I/Xposed  ( 1188): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
04-02 10:07:46.935 I/Xposed  ( 1188): Loading modules from /data/app/com.marz.snapprefs-1/base.apk
04-02 10:07:46.965 I/Xposed  ( 1188):   Loading class com.marz.snapprefs.HookMethods
04-02 10:07:53.815 I/Xposed  ( 1189): -----------------
04-02 10:07:53.815 I/Xposed  ( 1189): Starting Xposed version 87, compiled for SDK 23
04-02 10:07:53.815 I/Xposed  ( 1189): Device: HTC One M9 (HTC), Android version 6.0.1 (SDK 23)
04-02 10:07:53.815 I/Xposed  ( 1189): ROM: MMB29M release-keys
04-02 10:07:53.815 I/Xposed  ( 1189): Build fingerprint: htc/pmeuhl_00401/htc_pmeuhl:6.0.1/MMB29M/797255.3:user/release-keys
04-02 10:07:53.815 I/Xposed  ( 1189): Platform: arm64-v8a, 32-bit binary, system server: no
04-02 10:07:53.815 I/Xposed  ( 1189): SELinux enabled: yes, enforcing: no
04-02 10:07:55.914 I/Xposed  ( 1189): -----------------
04-02 10:07:55.914 I/Xposed  ( 1189): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
04-02 10:07:56.023 I/Xposed  ( 1189): Detected ART runtime
04-02 10:07:56.027 I/Xposed  ( 1189): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
04-02 10:07:56.462 I/Xposed  ( 1189): Loading modules from /data/app/com.marz.snapprefs-1/base.apk
04-02 10:07:56.487 I/Xposed  ( 1189):   Loading class com.marz.snapprefs.HookMethods
04-02 10:07:43.662 I/Xposed  ( 1188): -----------------
04-02 10:07:43.662 I/Xposed  ( 1188): Starting Xposed version 87, compiled for SDK 23
04-02 10:07:43.662 I/Xposed  ( 1188): Device: HTC One M9 (HTC), Android version 6.0.1 (SDK 23)
04-02 10:07:43.662 I/Xposed  ( 1188): ROM: MMB29M release-keys
04-02 10:07:43.662 I/Xposed  ( 1188): Build fingerprint: htc/pmeuhl_00401/htc_pmeuhl:6.0.1/MMB29M/797255.3:user/release-keys
04-02 10:07:43.662 I/Xposed  ( 1188): Platform: arm64-v8a, 64-bit binary, system server: yes
04-02 10:07:43.662 I/Xposed  ( 1188): SELinux enabled: yes, enforcing: no
04-02 10:07:46.041 I/Xposed  ( 1188): -----------------
04-02 10:07:46.041 I/Xposed  ( 1188): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
04-02 10:07:46.312 I/Xposed  ( 1188): Detected ART runtime
04-02 10:07:46.333 I/Xposed  ( 1188): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
04-02 10:07:46.935 I/Xposed  ( 1188): Loading modules from /data/app/com.marz.snapprefs-1/base.apk
04-02 10:07:46.965 I/Xposed  ( 1188):   Loading class com.marz.snapprefs.HookMethods
04-02 10:07:53.815 I/Xposed  ( 1189): -----------------
04-02 10:07:53.815 I/Xposed  ( 1189): Starting Xposed version 87, compiled for SDK 23
04-02 10:07:53.815 I/Xposed  ( 1189): Device: HTC One M9 (HTC), Android version 6.0.1 (SDK 23)
04-02 10:07:53.815 I/Xposed  ( 1189): ROM: MMB29M release-keys
04-02 10:07:53.815 I/Xposed  ( 1189): Build fingerprint: htc/pmeuhl_00401/htc_pmeuhl:6.0.1/MMB29M/797255.3:user/release-keys
04-02 10:07:53.815 I/Xposed  ( 1189): Platform: arm64-v8a, 32-bit binary, system server: no
04-02 10:07:53.815 I/Xposed  ( 1189): SELinux enabled: yes, enforcing: no
04-02 10:07:55.914 I/Xposed  ( 1189): -----------------
04-02 10:07:55.914 I/Xposed  ( 1189): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
04-02 10:07:56.023 I/Xposed  ( 1189): Detected ART runtime
04-02 10:07:56.027 I/Xposed  ( 1189): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
04-02 10:07:56.462 I/Xposed  ( 1189): Loading modules from /data/app/com.marz.snapprefs-1/base.apk
04-02 10:07:56.487 I/Xposed  ( 1189):   Loading class com.marz.snapprefs.HookMethods
04-02 10:10:33.357 I/Xposed  ( 9963): ----------------- SNAPPREFS HOOKED -----------------
04-02 10:10:33.366 I/Xposed  ( 9963): SnapChat Version: 9.35.5.0 (889)
04-02 10:10:33.366 I/Xposed  ( 9963): SnapPrefs Version: 2.1.0 (26)
04-02 10:10:33.599 I/Xposed  ( 9963): Snapprefs: [Forced] Performing LogType load
04-02 10:10:33.655 I/Xposed  ( 9963): Snapprefs: [Forced] Loaded [FORCED, DEBUG, GROUPS, PREFS, LENS, SAVING, FILTER, CHAT, DATABASE, PREMIUM] log types
04-02 10:10:33.656 I/Xposed  ( 9963): Snapprefs: [Debug] Loading map from xposed
04-02 10:10:33.659 I/Xposed  ( 9963): Snapprefs: [Prefs] XPrefs file exists: /data/data/com.marz.snapprefs/shared_prefs/com.marz.snapprefs_preferences.xml
04-02 10:10:33.659 I/Xposed  ( 9963): Snapprefs: [Prefs] Loading preferences
04-02 10:10:33.659 I/Xposed  ( 9963): Snapprefs: [Prefs] Null preferences... Creating new
04-02 10:10:33.659 I/Xposed  ( 9963): Snapprefs: [Prefs] Package name: com.marz.snapprefs
04-02 10:10:33.660 I/Xposed  ( 9963): Snapprefs: [Prefs] Making readable
04-02 10:10:33.662 I/Xposed  ( 9963): Snapprefs: [Prefs] Starting spin locker
04-02 10:10:33.662 I/Xposed  ( 9963): Snapprefs: [Prefs] Completed 200 spins
04-02 10:10:33.662 I/Xposed  ( 9963): Snapprefs: [Prefs] loading preference map: true
04-02 10:10:33.662 I/Xposed  ( 9963): Snapprefs: [Prefs] Map size: 56
04-02 10:10:33.663 I/Xposed  ( 9963): Snapprefs: [Debug] Application hook: com.snapchat.android.AppShell
04-02 10:10:33.666 E/Xposed  ( 9963): java.lang.NoSuchMethodError: abc#handleMessage(android.os.Message)#exact
04-02 10:10:33.666 E/Xposed  ( 9963): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:341)
04-02 10:10:33.666 E/Xposed  ( 9963): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:182)
04-02 10:10:33.666 E/Xposed  ( 9963): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:257)
04-02 10:10:33.666 E/Xposed  ( 9963): 	at com.marz.snapprefs.HookMethods$3.afterHookedMethod(HookMethods.java:299)
04-02 10:10:33.666 E/Xposed  ( 9963): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
04-02 10:10:33.666 E/Xposed  ( 9963): 	at android.app.Application.attach(<Xposed>)
04-02 10:10:33.666 E/Xposed  ( 9963): 	at android.app.Instrumentation.newApplication(Instrumentation.java)
04-02 10:10:33.666 E/Xposed  ( 9963): 	at android.app.Instrumentation.newApplication(Instrumentation.java)
04-02 10:10:33.666 E/Xposed  ( 9963): 	at android.app.LoadedApk.makeApplication(LoadedApk.java)
04-02 10:10:33.666 E/Xposed  ( 9963): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java)
04-02 10:10:33.666 E/Xposed  ( 9963): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
04-02 10:10:33.666 E/Xposed  ( 9963): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
04-02 10:10:33.666 E/Xposed  ( 9963): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
04-02 10:10:33.666 E/Xposed  ( 9963): 	at android.app.ActivityThread.access$1600(ActivityThread.java)
04-02 10:10:33.666 E/Xposed  ( 9963): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
04-02 10:10:33.666 E/Xposed  ( 9963): 	at android.os.Handler.dispatchMessage(Handler.java)
04-02 10:10:33.666 E/Xposed  ( 9963): 	at android.os.Looper.loop(Looper.java)
04-02 10:10:33.666 E/Xposed  ( 9963): 	at android.app.ActivityThread.main(ActivityThread.java)
04-02 10:10:33.666 E/Xposed  ( 9963): 	at java.lang.reflect.Method.invoke(Native Method)
04-02 10:10:33.666 E/Xposed  ( 9963): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
04-02 10:10:33.666 E/Xposed  ( 9963): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
04-02 10:10:33.666 E/Xposed  ( 9963): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
04-02 10:10:34.623 I/Xposed  ( 9963): Snapprefs: [Debug] Updating view_snap.snap_container layout
04-02 10:10:35.074 E/Xposed  ( 9963): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.app.Activity.getResources()' on a null object reference
04-02 10:10:35.074 E/Xposed  ( 9963): 	at com.marz.snapprefs.HookedLayouts.px(HookedLayouts.java:568)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at com.marz.snapprefs.HookedLayouts$3.handleLayoutInflated(HookedLayouts.java:175)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at de.robv.android.xposed.callbacks.XC_LayoutInflated.call(XC_LayoutInflated.java:57)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.content.res.XResources$2.afterHookedMethod(XResources.java:219)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.LayoutInflater.inflate(<Xposed>)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.LayoutInflater.inflate(LayoutInflater.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at Us.<init>(SourceFile:219)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at Us.<init>(SourceFile:185)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at com.snapchat.android.camera.CameraFragment.a(SourceFile:661)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at com.snapchat.android.camera.BaseCameraFragment.onCreateView(SourceFile:94)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at com.snapchat.android.camera.CameraFragment.onCreateView(SourceFile:473)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.support.v4.app.Fragment.performCreateView(SourceFile:1974)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at ae.a(SourceFile:1067)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at ae.a(SourceFile:1252)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at Z.run(SourceFile:738)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at ae.i(SourceFile:1617)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at ae.b(SourceFile:570)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at asb.finishUpdate(SourceFile:118)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at ws.finishUpdate(SourceFile:124)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.support.v4.view.ViewPager.populate(SourceFile:1177)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.support.v4.view.ViewPager.populate(SourceFile:1025)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.support.v4.view.ViewPager.onMeasure(SourceFile:1545)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.View.measure(View.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.View.measure(View.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.View.measure(View.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.View.measure(View.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.View.measure(View.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.View.measure(View.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.Choreographer.doCallbacks(Choreographer.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.Choreographer.doFrame(Choreographer.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.os.Handler.handleCallback(Handler.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.os.Handler.dispatchMessage(Handler.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.os.Looper.loop(Looper.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at android.app.ActivityThread.main(ActivityThread.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at java.lang.reflect.Method.invoke(Native Method)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
04-02 10:10:35.074 E/Xposed  ( 9963): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
04-02 10:10:35.918 I/Xposed  ( 9963): Snapprefs: [Debug] Cached friendmoji match!

**Comment by RyanBrogan** [comment]
Um... 9.35.5.. My bad
