### ISSUE TITLE
Snapchat 9.39.5.0 crashes with Snapprefs 2.1.0 on official Xposed release for Nougat

### ISSUE THREAD

**Issue by sundownsong** [marzika/Snapprefs#398]
## Expected Behavior
Snapchat should successfully launch when Snapprefs is enabled 

## Current Behavior
Snapchat 9.39.5.0 crashes with Snapprefs 2.1.0 on official Xposed release for Nougat

## Your Environment

* Version used:  Snapchat 9.39.5.0, Snapprefs 2.1.0 
* Android version:  Lineage 14.1 - lineage-14.1-20171005-nightly-mako-signed
* Xposed version and type (systemless or regular)  Xposed SDK25 ARM and apk v 3.12
* Root version and type (SuperSU, phh, etc. and system or systemless):  Addon SU - https://download.lineageos.org/extras
* Do you use any root/xposed hiding? If yes, which?: Rootcloak installed but not loaded

Wiped phone from CM13 with TWRP, copied image over, and flashed with clean LineageOS image, installed apps, started snapchat.  Installed xposed and modules including snapprefs aftewards.

Logcat attached for start of snapchat onwards, not sure if it's a snapprefs or xposed bug:

```
10-13 11:47:12.587  3238  3238 D AndroidRuntime: Shutting down VM
--------- beginning of crash
10-13 11:47:12.591  3238  3238 E AndroidRuntime: FATAL EXCEPTION: main
10-13 11:47:12.591  3238  3238 E AndroidRuntime: Process: com.snapchat.android, PID: 3238
10-13 11:47:12.591  3238  3238 E AndroidRuntime: java.lang.SecurityException: Package android not in UID 10094
10-13 11:47:12.591  3238  3238 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1684)
10-13 11:47:12.591  3238  3238 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1637)
10-13 11:47:12.591  3238  3238 E AndroidRuntime:        at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:829)
10-13 11:47:12.591  3238  3238 E AndroidRuntime:        at android.view.ViewRootImpl.setView(ViewRootImpl.java:640)
10-13 11:47:12.591  3238  3238 E AndroidRuntime:        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
10-13 11:47:12.591  3238  3238 E AndroidRuntime:        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
10-13 11:47:12.591  3238  3238 E AndroidRuntime:        at android.widget.Toast$TN.handleShow(Toast.java:459)
10-13 11:47:12.591  3238  3238 E AndroidRuntime:        at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
10-13 11:47:12.591  3238  3238 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
10-13 11:47:12.591  3238  3238 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
10-13 11:47:12.591  3238  3238 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
10-13 11:47:12.591  3238  3238 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-13 11:47:12.591  3238  3238 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
10-13 11:47:12.591  3238  3238 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
10-13 11:47:12.591  3238  3238 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
10-13 11:47:12.595   624  1098 W ActivityManager:   Force finishing activity com.snapchat.android/.LandingPageActivity
```
[logcat.txt](https://github.com/marzika/Snapprefs/files/1382478/logcat.txt)

**Comment by lgrootnoob** [comment]
This software is NOT supported. Please put it to rest

**Comment by miggsr** [comment]
Actually lgrootnoob.... This version of Snapprefs works PERFECTLY fine with Nougat. Also instead of complaining telling the developer to put it rest how about you provide some log with information on what issues you are having. That way it can be resolved when the dev has time to get to it. 

Also for anyone asking... I'm on Nougat with the unofficial xposed and I have Snapchat and Snapprefs working just fine. I'm currently on an HTC device.

**Comment by mronikoyi** [comment]
Indoor= unroot (auto correct)

**Comment by mronikoyi** [comment]
@miggsr, I have the same issue.
I remember speaking to the Dev while trying to get a refund through PayPal for the premium account because it didn't work, and that was the one time I got a reaction from him, explaining how I had to indoor my phone, install an old Snapchat, log on then root the phone again.
He then told me that he would update Snapprefs before September 2017. He then asked me to remove my issue on PayPal, which I  did. Since then no news or response by mail... A bit disappointed...

**Comment by marzika** [comment]
@mronikoyi Your issue was completly unrelated, since you had issues passing SafetyNet, which you have resolved therefore the Paypal case must be closed too. See: https://imgur.com/a/P9AwT

**Comment by mronikoyi** [comment]
Except that I passed the safetynet a while ago and that now Snapchat just crashes, hence the reason why I asked for updates

**Comment by stevesbrain** [comment]
@mronikoyi Is it consistent crashing? If had it where certain users stories will make mine crash until the story expires. It's not just a case of that, by any chance?

**Comment by mronikoyi** [comment]
@stevesbrain I just tried again, I get the ghost then it crashes. Maybe you're right, there's a story that is blocking me I don't know but it's just crashing like it would when you know you need to update your app!

**Comment by stevesbrain** [comment]
@mronikoyi Does it happen within moments of it starting, as soon as the blue/purple icons light up to show that there's content for you to view? Does it happen when it airplane mode?

**Comment by michaelrinos** [comment]
So I've been watching for a while since I have the same issue. Sc crashes as soon as I launch it. 

Some background I have Android nougat 7.1.2 with official rovo Xposed sdk 25 88.1 on a nexus 6p. Running latest version of snapreps with sc 9.39.5.0

If I turn on airplane mode I can get into Snapchat no chrash. But when I turn airplane off (in app or not) Snapchat crashes.

**Comment by michaelrinos** [comment]
@stevesbrain for me it chrashes after the yellow screen when the camera screen first appears and the UI for the camera shows up (the message/stories, circle to take snaps and other icons on top appear.

Not sure if this makes a difference but I get the location icon popping up in the notification tray right before it happens.

**Comment by stevesbrain** [comment]
@michaelrinos Yeah, that's the point where mine was doing it also. However, mine only lasted for the duration of that one story. I am also on Android 6.0.1. I believe that although Xposed itself works on Android 7, Snapprefs has been officially only supported on 6.0.1. Given that, you may not get anything in the way of "official" support with that configuration :( Is it possible as far as testing to update your app, see who has those stories, then get them to block you from their stories, then revert to old version and test? That would at least confirm if it's stories or not. 

Has it done it the whole time you've been on 7? Or was it working for some time? I've also had it where bad lenses enabled has caused a crash, so try disabling all lenses.

**Comment by michaelrinos** [comment]
@stevesbrain it's been the whole time I've been on 7. I'd be happy to post logs but I'm not sure where they are/how to get them. 
Otherwise I haven't tried updating and then reverting back.
I don't even have the lenses enabled so I doubt that those would cause the issue

**Comment by stevesbrain** [comment]
To be honest, I'd be likely thinking 7 is the cause then :( But, I haven't personally tried on 7, so cannot say conclusively :( I'd either revert to 6 for testing, or, wait for whenever the next update is! Sorry it's not better news!

**Comment by doonoo** [comment]
Thank god I never bought the premium, the developer got bitchy when people asked for updates then got lazy and stop updating.

**Comment by stevesbrain** [comment]
@doonoo Buying premium is not a guarantee of faster development though... it's an open source project, and it'll happen when it happens. Premium really just unlocks a few extra features + supports the dev. It's not like nothing has been happening; check commit history on the relevant branches.
