### ISSUE TITLE
[bug] Snapprefs text customization options

### ISSUE THREAD

**Issue by AmineI** [marzika/Snapprefs#81]
Hi ! 
While trying all the text customisations features, I faced two issues :
- The 'font customisation' button is unresponsive, tapping on it won't do anything
- Trying to use  the 'Background transparency' button crashes Snapchat

Xposed log won't show anything, and I don't really know if I should take the Snapprefs log or the snapchat log.
Thank you for your time !

**Comment by NightMean** [comment]
Post logcat

**Comment by marzika** [comment]
The log must be taken from the app that crashes and that is Snapchat. Make sure you already have font files in the designated folder.

**Comment by AmineI** [comment]
Here's the interesting part :

```
05-06 17:22:43.605 ? W:     at com.marz.snapprefs.HookedLayouts$OptionsAdapter$1.onClick(HookedLayouts.java:696)
05-06 17:22:43.613 ? W: End session with context: com.snapchat.android.LandingPageActivity@42cf8b80 count:0
05-06 17:22:43.621 ? E: FATAL EXCEPTION: main
                        java.lang.NoSuchMethodError: android.graphics.drawable.Drawable.getAlpha
                            at com.marz.snapprefs.HookedLayouts$OptionsAdapter$1.onClick(HookedLayouts.java:696)
                            at android.view.View.performClick(View.java:4452)
                            at android.view.View$PerformClick.run(View.java:18428)
                            at android.os.Handler.handleCallback(Handler.java:725)
                            at android.os.Handler.dispatchMessage(Handler.java:92)
                            at android.os.Looper.loop(Looper.java:176)
                            at android.app.ActivityThread.main(ActivityThread.java:5365)
                            at java.lang.reflect.Method.invokeNative(Native Method)
                            at java.lang.reflect.Method.invoke(Method.java:511)
                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
                            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
                            at dalvik.system.NativeStart.main(Native Method)
05-06 17:22:43.722 ? D: processName: com.snapchat.android
05-06 17:22:43.722 ? D: broadcastEvent : com.snapchat.android data_app_crash
```

**Comment by marzika** [comment]
http://developer.android.com/reference/android/graphics/drawable/Drawable.html#getAlpha()
getAlpha() was introduced in Kitkat, that's why it crashes. I would seriously suggest you to upgrade your device or the ROM, as you will experience less features and lag on further versions. Also, support will be dropped for devices below Kitkat.

https://github.com/marzika/Snapprefs/commit/ec3b3a01357abe0d1e78640acac95ed6cc1a06bc

**Comment by AmineI** [comment]
Ok, good to know !
Thank you for the suggestion, but I can't upgrade my ROM since I use a low-end Samsung device with no support, I even tried to build a CM for my phone without success, so I gave up about that.

A quick question then : When you say "Support dropped for below KitKat", do you mean that the issues with these devices just won't be fixed, or that you'll compile the app using the minSDK 19 ?

**Comment by marzika** [comment]
MinSDK 19, Snapchat already drops main features for Lollipop and below.

**Comment by AmineI** [comment]
Aouch, okay. When will it happen ? Next version already ?

**Comment by AmineI** [comment]
Ah, I almost forgot the other issue :
The unresponsive 'font customisation' button is also related to my Android version ? The log won't show anything when about it.

**Comment by marzika** [comment]
When Snapchat will stop supporting them, it will not be that long until that.
